### ISSUE TITLE
Is there something wrong with 'static_pon_setting.yml'

### ISSUE THREAD

**Issue by gao-shi** [wayveai/fiery#16]
In static_pon_setting.yml, config is 
```
_BASE_: 'lift_splat_setting.yml'

TAG: 'pyramid_occupancy_network_setting'

LIFT:
  X_BOUND: [-50.0, 50.0, 0.25]
  Y_BOUND: [-25.0, 25.0, 0.25]
```

But i think _BASE should be single_timeframe.yml， and FILTER_INVISIBLE_VEHICLES: False
